### ISSUE TITLE
Is `wsfr_download` package available in runtime?

### ISSUE THREAD

**Issue by rasyidstat** [drivendataorg/water-supply-forecast-rodeo-runtime#16]
Hi @jayqi, is `wsfr_download` package available in runtime?

I got this following error `ModuleNotFoundError: No module named 'wsfr_download'`

**Comment by jayqi** [comment]
Hi @rasyidstat,

`wsfr_download` is _not_ available in the runtime. We use `wsfr_download` to prepopulate the mounted data drive that contains test features. All of the data that from running `python -m wsfr_download bulk data_download/hindcast_test_config.yml` is present and can be read from disk. 

If you would like to leverage some of the code in `wsfr_download` for direct-API-access data sources, you can copy or vendor the relevant modules or functions. In general, each module within `wsfr_download` is pretty self-contained aside from occasional dependencies on `wsfr_download.utils`.
