### ISSUE TITLE
Add zeep and stamina

### ISSUE THREAD

**Issue by rasyidstat** [drivendataorg/water-supply-forecast-rodeo-runtime#18]
Hi @jayqi, could you please add `zeep` and `stamina` to the runtime?

Thanks

**Comment by jayqi** [comment]
@rasyidstat — Can you please clarify why you need zeep and stamina? Is this for SNOTEL data? Are you using data from SNOTEL stations that we aren't predownloading?

**Comment by rasyidstat** [comment]
Hi @jayqi, yes it's for downloading SNOTEL data. There are some missing SNOTEL stations since I used different approach to get the pair between sites. 
Previously, I can handle it by filtering stations that only available in runtime. 

I also have a few question to clarify in the forum.

**Comment by jayqi** [comment]
All set as of https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime/commit/5d455129977f64a17f1309c5546b1cd01327717b
