### ISSUE TITLE
Data reading script for SNODAS, SNOTEL, CDEC

### ISSUE THREAD

**Issue by ritviksahajpal** [drivendataorg/water-supply-forecast-rodeo-runtime#2]
Thanks for providing excellent data download and reading capabilities. Are you also planning to release data reading scripts for SNODAS, SNOTEL and CDED variables?

**Comment by jayqi** [comment]
Hi @ritviksahajpal,

The data reading code is sample code that is provided to be helpful for getting started. We may not provide data reading code for all datasets, so you should not depend on data reading code being added for any particular data source.

**Comment by jayqi** [comment]
Closing this issue to reflect that participants should not expect these items to be provided.
