### ISSUE TITLE
I would like to be able to use R for this project

### ISSUE THREAD

**Issue by eli-asarian** [drivendataorg/water-supply-forecast-rodeo-runtime#5]
I would like to be able to use R for this project. I saw the note that "Code written in R is permitted for this challenge, but the initial runtime environment specification does not include any R dependencies for simplicity. If you need R, please open an issue in the runtime repository and challenge organizers will work with you to add it" so that is what I am doing here.  I do not have any Python experience, is there a way run this completely in R Studio, the environmental I typically use for my analyses? Alternatively, I do have Team members who do have Python experience, so we probably could figure out how to run R from within Python if that is allowed. From my brief research on this topic, it looks like the Python rpy2 package is the best way to run R within Python, but according to https://rviews.rstudio.com/2022/05/25/calling-r-from-python-with-rpy2/, that requires Python >=3.7 whereas this context requires Python 3.10.13? One thing we might want to do is do the data pre-processing is Python but do the predictions in R.

**Comment by jayqi** [comment]
Hi @eli-asarian, R v4.3.2 is availabe in the runtime environment as of [this commit](https://github.com/drivendataorg/water-supply-forecast-rodeo-runtime/commit/468090f70723029e03023142e989f4f923481c24). I will address your requests for packages in #13.
